services:
    app:
        user: app
        build:
            context: ./docker/php
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
