services:
    app:
        user: app
        build:
            context: ./docker/php
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
    database:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
        volumes:
            - database_data:/var/mysql/data:rw

volumes:
    database_data: